

Drupal database update
The Hooded Hare
Installation tasks

    Verify requirements(done)
    Overview(done)
    Review updates(active)
    Run updates
    Review log

The version of Drupal you are updating from has been automatically detected.
3 pending updates
system module

    7078 - Add binary to {date_formats}.format.

dblog module

    7002 - Add an index to the severity column in the watchdog database table.

field module

    7003 - Add the FieldInfo class to the class registry.


had to reload DB update page (above) to see 
update progress bar & completion message

