; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.14"

; Modules
projects[ctools][version] = "1.0"

projects[entity][version] = "1.0-rc3"

projects[rules][version] = "2.1"

projects[ubercart][version] = "3.1"

projects[token][version] = "1.1"

projects[views][version] = "3.3"

; Themes
projects[acquia_prosper][version] = "1.x-dev"

projects[zen][version] = "5.1"

